const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  DECREASE_ITEM_QUANTITY: "DECREASE_ITEM_QUANTITY",
  DELETE_ITEM_FROM_CART: "DELETE_ITEM_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
};

export default CartActionTypes;
